CREATE TABLE categories (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE menu_items (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	category_id BIGINT NOT NULL REFERENCES categories(id),
	name TEXT NOT NULL UNIQUE,
	price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
	is_available BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
